import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { QuoicouBeatsGeneratedModule, QuoicouBeatsGeneratedSharedModule } from './generated/module.js';
import { QuoicouBeatsValidator, registerValidationChecks } from './quoicou-beats-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type QuoicouBeatsAddedServices = {
    validation: {
        QuoicouBeatsValidator: QuoicouBeatsValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type QuoicouBeatsServices = LangiumServices & QuoicouBeatsAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const QuoicouBeatsModule: Module<QuoicouBeatsServices, PartialLangiumServices & QuoicouBeatsAddedServices> = {
    validation: {
        QuoicouBeatsValidator: () => new QuoicouBeatsValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createQuoicouBeatsServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    QuoicouBeats: QuoicouBeatsServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        QuoicouBeatsGeneratedSharedModule
    );
    const QuoicouBeats = inject(
        createDefaultModule({ shared }),
        QuoicouBeatsGeneratedModule,
        QuoicouBeatsModule
    );
    shared.ServiceRegistry.register(QuoicouBeats);
    registerValidationChecks(QuoicouBeats);
    return { shared, QuoicouBeats };
}
